[window]
decorations = "Buttonless"
padding = { x = 12, y = 12 }
dynamic_title = true

[scrolling]
history = 80000

[font]
normal = { family = "MonoLisa Nerd Font", style = "Regular" }
bold = { family = "MonoLisa Nerd Font", style = "Bold" }
italic = { family = "MonoLisa Nerd Font", style = "Regular Italic" }
bold_italic = { family = "MonoLisa Nerd Font", style = "Bold Italic" }
size = 12
