[window]
decorations = "Buttonless"
padding = { x = 12, y = 12 }
dynamic_title = true

[scrolling]
history = 80000

[font]
normal = { family = "Berkeley Mono", style = "Regular" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Regular Italic" }
bold_italic = { family = "Berkeley Mono", style = "Bold Italic" }
size = 14

[colors.primary]
foreground = "#D9D6DE"
background = "#1C1C22"

[colors.cursor]
text = "#D9D6DE"
cursor = "#DED5C8"
